[project]
name = 'first-clarity-project'
requirements = []

[contracts.faucet]
path = 'contracts/faucet.clar'

[contracts.tipjar]
path = 'contracts/tipjar.clar'

[contracts.greeting]
path = 'contracts/greeting.clar'
